[project]
name = "try-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "ocrmac>=1.0.0",
  "pillow>=11.2.1",
  "pytesseract>=0.3.13",
]

[tool.uv.workspace]
members = [
  "packages/pytess",
  "packages/try-ocrmac",
]
