[project]
name = "try-ocrmac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "ocrmac>=1.0.0",
]

[project.scripts]
try-ocrmac = "try-ocrmac:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
